

services:

  spring-boot:
    build: ./
    container_name: spring-boot

  mongo:
    image: mongo:3.7.2
    container_name: mongo
    ports:
      - 27017:27017

  activemq:
    image: webcenter/activemq:5.14.3
    container_name: activemq
    ports:
      - 15672:8161
      - 5671:5671
      - 5672:5672
      - 61616:61616

  configserver:
    image: hyness/spring-cloud-config-server
    container_name: configserver
    ports:
      - 8888:8888
    volumes:
      - "D:/code/config:/config"
    environment:
      - SPRING_PROFILES_ACTIVE=native


